### ISSUE TITLE
when browsing stops or routes by operator name, filter to only list operators with `import_level` >= 1

### ISSUE THREAD

**Issue by drewda** [transitland/playground#137]
Addresses a bug reported by https://twitter.com/pietercolpaert/status/715491920739504128

Now possible on back-end, thanks to https://github.com/transitland/transitland-datastore/issues/472

**Comment by meghanhade** [comment]
A fix to https://github.com/transitland/transitland-datastore/issues/540 will impact this as well. (cc @irees)

**Comment by meghanhade** [comment]
@drewda could you please review the approached used here in PR https://github.com/transitland/playground/pull/138?
